### ISSUE TITLE
Quickly pressing the "Refresh Places" button can cause a crash.

### ISSUE THREAD

**Issue by ghost** [BttrDrgn/radio.garten#2]
Hit or miss on whether or not it crashes, can crash on 2, 3, or multiple clicks.

### How to reproduce:
 Quickly click the "Refresh Places" button under "Actions"

### Information
**Release: v0.3.1**
**Operating System: Windows 11 Pro**

https://user-images.githubusercontent.com/88047121/167976400-312eca3c-96f6-425b-a218-84febaaf7607.mp4

**Comment by BttrDrgn** [comment]
Thanks! Will be fixed next release.
